services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "3456:5432"
    environment:
      POSTGRES_USER: ecoshop
      POSTGRES_PASSWORD: ecoshop_password
      POSTGRES_DB: ecoshop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pyroscope:
    image: grafana/pyroscope:latest
    restart: unless-stopped
    ports:
      - "4040:4040"

volumes:
  postgres_data:
